monolog:
    channels: ["orm"]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        OrmLogger:
            type: service
            id: orm_handler
            channels: [ "orm" ]
            level: info
            priority: 0

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

services:
    orm_handler:
        class: App\Logger\OrmLogger
        arguments:
          [ '@doctrine.orm.entity_manager' ]
